# ==================================================================
# QUANTUM'S KUSTOMIZATION BASE
# Base configuration for all environments
# ==================================================================

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: astral-turf-base
  annotations:
    config.kubernetes.io/local-config: "true"

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - nginx-deployment.yaml
  - service.yaml
  - hpa.yaml
  - vpa.yaml
  - cluster-autoscaler.yaml
  - ingress.yaml
  - networkpolicy.yaml
  - poddisruptionbudget.yaml
  - servicemonitor.yaml
  - disaster-recovery.yaml
  - global-cdn-edge.yaml
  - chaos-engineering.yaml
  - sre-runbooks.yaml

commonLabels:
  app.kubernetes.io/name: astral-turf
  app.kubernetes.io/part-of: astral-turf-platform
  app.kubernetes.io/managed-by: kustomize

commonAnnotations:
  kubernetes.io/managed-by: "quantum-infrastructure"
  deployment.kubernetes.io/revision: "1"

images:
  - name: astral-turf
    newTag: latest

# Namespace for all resources
namespace: astral-turf

# Configuration transformers
configMapGenerator:
  - name: build-info
    literals:
      - BUILD_DATE="2024-01-01T00:00:00Z"
      - GIT_COMMIT="latest"
      - VERSION="8.0.0"

secretGenerator:
  - name: app-secrets
    type: Opaque
    files:
      - .env.production

# Resource patches
patchesStrategicMerge:
  - patches/resource-limits.yaml

# JSON 6902 patches
patchesJson6902:
  - target:
      version: v1
      kind: Service
      name: astral-turf-service
    path: patches/service-annotations.yaml

# Replacements
replacements:
  - source:
      kind: ConfigMap
      name: build-info
      fieldPath: data.VERSION
    targets:
      - select:
          kind: Deployment
          name: astral-turf-app
        fieldPaths:
          - spec.template.metadata.labels.[app.kubernetes.io/version]