# ==================================================================
# QUANTUM'S POD DISRUPTION BUDGETS
# Ensure high availability during maintenance and scaling
# ==================================================================

apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: astral-turf-pdb
  namespace: astral-turf
  labels:
    app.kubernetes.io/name: astral-turf
    app.kubernetes.io/component: disruption-budget
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: astral-turf
      app.kubernetes.io/component: application

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: nginx-pdb
  namespace: astral-turf
  labels:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/component: disruption-budget
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx
      app.kubernetes.io/component: loadbalancer